### ISSUE TITLE
Using an unknown "due" value results in a crash

### ISSUE THREAD

**Issue by geekpete** [laktak/todd#11]
I'd tried `due:tomorrow` and it crashed with:

```
Traceback (most recent call last):
  File "/home/peter/.local/bin/todd", line 11, in <module>
    sys.exit(main())
  File "/home/peter/.local/lib/python3.6/site-packages/todd/main.py", line 132, in main
    view.main(enable_word_wrap)  # start up the urwid UI event loop
  File "/home/peter/.local/lib/python3.6/site-packages/todd/taskui/main_ui.py", line 467, in main
    self.loop.run()
  File "/home/peter/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/home/peter/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/home/peter/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 788, in run
    self._loop()
  File "/home/peter/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 825, in _loop
    self._watch_files[fd]()
  File "/home/peter/.local/lib/python3.6/site-packages/urwid/raw_display.py", line 404, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/home/peter/.local/lib/python3.6/site-packages/urwid/raw_display.py", line 502, in parse_input
    callback(processed, processed_codes)
  File "/home/peter/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 411, in _update
    self.process_input(keys)
  File "/home/peter/.local/lib/python3.6/site-packages/urwid/main_loop.py", line 511, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/home/peter/.local/lib/python3.6/site-packages/urwid/container.py", line 2271, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/home/peter/.local/lib/python3.6/site-packages/urwid/container.py", line 1131, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/home/peter/.local/lib/python3.6/site-packages/todd/taskui/components.py", line 116, in keypress
    key = super(ViListBox, self).keypress(size, key)
  File "/home/peter/.local/lib/python3.6/site-packages/urwid/listbox.py", line 999, in keypress
    key = focus_widget.keypress((maxcol,),key)
  File "/home/peter/.local/lib/python3.6/site-packages/todd/taskui/taskitem.py", line 103, in keypress
    self.end_edit()
  File "/home/peter/.local/lib/python3.6/site-packages/todd/taskui/taskitem.py", line 96, in end_edit
    self.parent_ui.task_changed()
  File "/home/peter/.local/lib/python3.6/site-packages/todd/taskui/main_ui.py", line 266, in task_changed
    t.update_relative_due_date()
  File "/home/peter/.local/lib/python3.6/site-packages/todd/tasklib/task.py", line 191, in update_relative_due_date
    date = Util.mod_date_by(Util.get_today(), match.group(1))
  File "/home/peter/.local/lib/python3.6/site-packages/todd/tasklib/util.py", line 91, in mod_date_by
    (prefix, value, itype) = Util._interval_parts_regex.match(text).groups()
AttributeError: 'NoneType' object has no attribute 'groups'
```

A python library like [Arrow](https://github.com/crsmithdev/arrow/) might make the time conversions a cinch if you wanted to grab human readable date/time values and try to convert them.

Either way, the app should do something graceful if a bad due value is entered.

**Comment by laktak** [comment]
Thanks for the input, I didn't know about Arrow. I fixed the crash for now but I might come back to this later.

**Comment by geekpete** [comment]
So using a totally weird due date value like some random string appears fixed, but using an invalid date eg 2019-04-31 breaks still with:

```
  File "/home/peter/Code/todd/todd/taskui/taskitem.py", line 38, in update_task
    due_name = Util.get_date_name(t.get_due(), today=today)
  File "/home/peter/Code/todd/todd/tasklib/task.py", line 184, in get_due
    datetime.datetime.strptime(self.due_date, "%Y-%m-%d").date() if self.due_date else None
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 528, in _strptime
    datetime_date(year, 1, 1).toordinal() + 1
ValueError: day is out of range for month
```
