### ISSUE TITLE
Hitting edit on a view with no tasks listed causes a crash

### ISSUE THREAD

**Issue by geekpete** [laktak/todd#2]
If there's no tasks in the current view then you hit enter to edit, it'll crash with:

```
Traceback (most recent call last):
  File "/usr/local/bin/todd", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/todd/main.py", line 129, in main
    view.main(enable_word_wrap)  # start up the urwid UI event loop
  File "/usr/local/lib/python3.7/site-packages/todd/taskui/main_ui.py", line 369, in main
    self.loop.run()
  File "/usr/local/lib/python3.7/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/usr/local/lib/python3.7/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/usr/local/lib/python3.7/site-packages/urwid/main_loop.py", line 788, in run
    self._loop()
  File "/usr/local/lib/python3.7/site-packages/urwid/main_loop.py", line 825, in _loop
    self._watch_files[fd]()
  File "/usr/local/lib/python3.7/site-packages/urwid/raw_display.py", line 404, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/local/lib/python3.7/site-packages/urwid/raw_display.py", line 502, in parse_input
    callback(processed, processed_codes)
  File "/usr/local/lib/python3.7/site-packages/urwid/main_loop.py", line 411, in _update
    self.process_input(keys)
  File "/usr/local/lib/python3.7/site-packages/urwid/main_loop.py", line 517, in process_input
    something_handled |= bool(self.unhandled_input(k))
  File "/usr/local/lib/python3.7/site-packages/urwid/main_loop.py", line 563, in unhandled_input
    return self._unhandled_input(input)
  File "/usr/local/lib/python3.7/site-packages/todd/taskui/main_ui.py", line 343, in keystroke
    elif self.key_bindings.is_bound_to(key, "edit"): self.edit_task()
  File "/usr/local/lib/python3.7/site-packages/todd/taskui/main_ui.py", line 197, in edit_task
    focus.edit_item(normal_mode)
AttributeError: 'NoneType' object has no attribute 'edit_item'
```

So do a search with something that returns empty results and then try to edit to reproduce this.

**Comment by laktak** [comment]
Thanks. Should be fixed with a few other issues as well.
